warehouse:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: demo3699
      port: 5432
      schema: public
      threads: 4
      type: postgres
      user: postgres
  target: dev
